### ISSUE TITLE
onEnd firing randomly when not scrolling a big list, when moving the table

### ISSUE THREAD

**Issue by jasonkneen** [Topener/nl.fokkezb.infiniteScroll#32]
I have a tableview with 2 items in it, if I move the tableview at all, the onEnd fires, if I click it - it also fires causing paging to go crazy.

**Comment by FokkeZB** [comment]
The problem is here:
https://github.com/FokkeZB/nl.fokkezb.infiniteScroll/blob/master/controllers/widget.js#L170

It triggers as soon as you scroll down. It should however, indeed also take the content height in consideration and not trigger in that case (though you should still be able to tap it).

PR welcome :)

**Comment by nitishdhar** [comment]
Hey, I see you have mentioned what's causing it. Is this the expected behavior or content height was taken into consideration in some release?

**Comment by FokkeZB** [comment]
@nitishdhar not sure yet how to exactly fix this (edge) case.

**Comment by Topener** [comment]
I'm closing this ticket due to inactivity. A proper workaround is callback handling and triggering the `done` method if there actually is no more data.

Just like @FokkeZB I don't know how to fix this edge case, so any PR's regarding this are still welcome
