### ISSUE TITLE
Android Error : widget.js line 72 : Uncaught TypeError: Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by SkipperJohn-whqjvaap** [Topener/nl.fokkezb.infiniteScroll#41]
SDK 4.1.0.GA

---

[ERROR] :  TiExceptionHandler: (main) [21540,58998] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,58998] - In alloy/widgets/nl.fokkezb.infiniteScroll/controllers/widget.js:42,69
[ERROR] :  TiExceptionHandler: (main) [0,58998] - Message: Uncaught TypeError: Cannot read property 'items' of undefined
[ERROR] :  TiExceptionHandler: (main) [0,58998] - Source:    var itemIndex = Math.max(parentSymbol.sections[sectionIndex].items.len
[ERROR] :  V8Exception: Exception occurred at alloy/widgets/nl.fokkezb.infiniteScroll/controllers/widget.js:42: Uncaught TypeError: Cannot read property 'items' of undefined

**Comment by FokkeZB** [comment]
Could you create a more complete test case that reproduces this error?

**Comment by Sandi89** [comment]
Hi Fokke,

Thank you for making this. I am experiencing the same issue as the OP on both iOS and Android platforms (although its much harder to recreate on Android). Also, when my app crashes on iOS there are no error logs provided. However, I am able to see stack trace through platform.appcelerator.com and It looks like this:

**Comment by FokkeZB** [comment]
Thanks @Sandi89. I must say I can't really find the exact code mentioned in the log. Are you running an older version? This is what is there when it comes to the marker:

https://github.com/FokkeZB/nl.fokkezb.infiniteScroll/blob/master/controllers/widget.js#L70-L86

Could you try to add some debugging logging around this? It seems like it is trying to get items of a section that doesn't exist. But as you can see in the code `sectionIndex = parentSymbol.sectionCount` so that should be ok.

**Comment by Sandi89** [comment]
Fokke, 

Yes, looks like i'm running older version as I dont have any null checks around that code.  Thanks for help!
