### ISSUE TITLE
Success Events not firing on Android (sometimes) if the ListView using the widget is not in focus

### ISSUE THREAD

**Issue by fahad86** [Topener/nl.fokkezb.infiniteScroll#62]

**Comment by Topener** [comment]
This is a user focussed widget, I would guess using infiniteScroll when the ListView is not in view indicates you can just work without this widget right?

**Comment by fahad86** [comment]
Well the view is initially loaded up and then the user finds the view loaded and continues interacting with it loading more data as they scroll to the bottom.

**Comment by fahad86** [comment]
I was able to fix this by changing the mark method as follows:

from:
`
    if(!_.isUndefined(parentSymbol.sectionCount) && parentSymbol.sectionCount > 0) {
      var sectionIndex = parentSymbol.sectionCount - 1;
      var itemIndex = Math.max(parentSymbol.sections[sectionIndex].items.length - 1);
`

to

`
    if(_.isArray(parentSymbol.sections) && parentSymbol.sections.length > 0) {
      var sectionIndex = parentSymbol.sections.length - 1;
      var itemIndex = Math.max(parentSymbol.sections[sectionIndex].items.length - 1);
`

the sectionCount seems to be unset when the view is not in focus (for Android)

**Comment by FokkeZB** [comment]
@fahad86 that seems like a Titanium bug then. If `sections` is not empty, then `sectionCount` shouldn't be either. I'd suggest filing this at https://jira.appcelerator.org/.

I'm not sure why, but at some point using `sections.length` instead of `sectionCount` didn't work out well on some OSes/versions. But if you could do some thorough testing and send a PR, I'm OK with merging it!
